name: inlabru_nbody
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _sysroot_linux-64_curr_repodata_hack
  - _tflow_select
  - abseil-cpp
  - absl-py
  - aiohappyeyeballs
  - aiohttp
  - aiosignal
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - astroml
  - astropy
  - asttokens
  - astunparse
  - async-lru
  - async-timeout
  - attrs
  - babel
  - backcall
  - beautifulsoup4
  - binutils_impl_linux-64
  - binutils_linux-64
  - blas
  - bleach
  - blinker
  - bottleneck
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - charset-normalizer
  - click
  - comm
  - contourpy
  - cryptography
  - cudatoolkit
  - cudnn
  - cupti
  - cupy
  - cycler
  - cyrus-sasl
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - exceptiongroup
  - executing
  - expat
  - fastrlock
  - filelock
  - flatbuffers
  - fontconfig
  - fonttools
  - freetype
  - frozenlist
  - fsspec
  - gast
  - gcc_impl_linux-64
  - gcc_linux-64
  - giflib
  - glib
  - glib-tools
  - gmp
  - gmpy2
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - grpc-cpp
  - grpcio
  - gst-plugins-base
  - gstreamer
  - gxx_impl_linux-64
  - gxx_linux-64
  - h11
  - h5py
  - hdf5
  - httpcore
  - httpx
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - keras
  - keras-preprocessing
  - kernel-headers_linux-64
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcups
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - libllvm14
  - libnghttp2
  - libopenblas
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libssh2
  - libstdcxx
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - lz4-c
  - magma
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mpc
  - mpfr
  - mpmath
  - multidict
  - mysql
  - nbclient
  - nbconvert
  - nbformat
  - nccl
  - ncurses
  - nest-asyncio
  - networkx
  - notebook
  - notebook-shim
  - numexpr
  - numpy
  - numpy-base
  - oauthlib
  - openjpeg
  - openssl
  - opt_einsum
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - ply
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - protobuf
  - psutil
  - ptyprocess
  - pure_eval
  - pyasn1
  - pyasn1-modules
  - pybind11-abi
  - pycparser
  - pyerfa
  - pygments
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-flatbuffers
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - qtconsole
  - qtpy
  - re2
  - readline
  - referencing
  - requests
  - requests-oauthlib
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - rsa
  - scikit-learn
  - seaborn
  - send2trash
  - setuptools
  - sip
  - six
  - snappy
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - sympy
  - sysroot_linux-64
  - tbb
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - termcolor
  - terminado
  - threadpoolctl
  - tinycss2
  - tk
  - tomli
  - torchtriton
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - urllib3
  - watchfiles
  - wcwidth
  - webencodings
  - websockets
  - wheel
  - wrapt