# Configuration for Pearson Correlation Coefficient Calculation

data:
  input_file: "/Users/r.kanaki/code/inlabru_nbody/data/micecat2_GC/micecat2_data_small.csv.bz2"
  output_file: "/home/rintaro/code/inlabru_nbody/output/micecat2_output/"

parameters:
  nsides: [16, 32, 64, 128, 256, 512, 1024] #Angular resolution of the map
  num_bins: 14 #Number of bins for redshift binning
