# Configuration for Pearson Correlation Coefficient Calculation

data:
  input_file: "/Users/r.kanaki/code/inlabru_nbody/data/micecat2_GC/micecat2_data_100.csv.bz2"
  output_file: "/Users/r.kanaki/code/inlabru_nbody/output/64_2048/"

parameters:
  nsides: [64, 128, 256, 512, 1024, 2048] #Angular resolution of the map
  num_bins: 14 #Number of bins for redshift binning
