input:
  json_file: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_DES_LSST_source_mag/RS_result/results_new_experiment.json"

output:
  directory: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_DES_LSST_source_mag/heatmap_new/"
  true_dir:
    heatmap_directory: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_DES_LSST_source_mag/heatmap_new/true/"
    results_directory: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_DES_LSST_source_mag/heatmap_new/true/results/"
  realization_dir:
    heatmap_directory: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_DES_LSST_source_mag/heatmap_new/realization/"
    results_directory: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_DES_LSST_source_mag/heatmap_new/realization/results/"