input:
  json_file: "/Users/r.kanaki/code/inlabru_nbody/output/LSST_Sampling_DES_true/RS_result/results_with_pvalues.json"

output:
  directory: "/Users/r.kanaki/code/inlabru_nbody/output/LSST_Sampling_DES_true/RS_result/heatmap"