input:
  json_file: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_schnell_debug/RS_result/results_old_experiment.json"

output:
  directory: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_schnell_debug/heatmap/"
  "true":
    heatmap_directory: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_schnell_debug/heatmap/true/"
    results_directory: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_schnell_debug/heatmap/true/results/"
  realization:
    heatmap_directory: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_schnell_debug/heatmap/realization/"
    results_directory: "/Users/r.kanaki/code/inlabru_nbody/output/micecat1_schnell_debug/heatmap/realization/results/"