input_path: "/Users/r.kanaki/code/inlabru_nbody/data/RV_Test/rs_16_DES_mag.csv.bz2"
output_path: 
  plots: "/Users/r.kanaki/code/inlabru_nbody/output/LSST_Sampling_DES_true_22_magcut/plots"
  high: "/Users/r.kanaki/code/inlabru_nbody/output/LSST_Sampling_DES_true_22_magcut/high_density.csv.bz2"
  low: "/Users/r.kanaki/code/inlabru_nbody/output/LSST_Sampling_DES_true_22_magcut/low_density.csv.bz2"
  random: "/Users/r.kanaki/code/inlabru_nbody/output/LSST_Sampling_DES_true_22_magcut/random_sampling.csv.bz2"
nside: 32